# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a862b2b3ccc3485bc70cc73d2200ad42e5c577081da6ad3564bd867a454aa04c6d732f8f4d1ea2f113f40f128bfdb4b4b44b3112ac446ccd7e18de64538efa

test:
  secret_key_base: ff1d0a6b27767fbcc233cf1fb87a0baaa066f16da0f8461bfcce7097d665a77c6f252df553d4e07f7c0ef58c58d58adf080a67cb52adcecaa99fd894ff58ee16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
